# Day 1

#### NumPy

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [3]:
# Creating numpy arrays

import numpy as np
arr = np.array([1, 2, 3, 4])

print(arr)

[1 2 3 4]


### 0-D Array

In [4]:
import numpy as np

arr = np.array(42)

print(arr)

42


# 1-D Array

In [12]:
import numpy as np
arr1 = np.array([1, 2, 3, 4])

print(arr)
print(arr1.ndim)


[[[1 2]
  [3 4]
  [5 6]]]
1


# 2-D Array

In [14]:
import numpy as np
arr2 = np.array([[1, 2], [3, 4]])

print(arr)
print(arr2.ndim)

[[[1 2]
  [3 4]
  [5 6]]]
2


# 3-D array

In [15]:
import numpy as np
arr3 = np.array([[[1, 2], [3, 4], [5,6]]])

print(arr)
print(arr3.ndim)

[[[1 2]
  [3 4]
  [5 6]]]
3


# numpy.save()

In [16]:
import numpy as np
a = np.array([1,2,3,4,5])   # make file outside 
np.save('outfile',a)

In [18]:
# load or check the file

import numpy as np
b = np.load('outfile.npy')
print(b)

[1 2 3 4 5]


In [20]:
import numpy as np

a = np.array([1,2,3,4,5])
print(type(a))
print(a.dtype)
np.savetxt('out.txt',a)
b = np.loadtxt('out.txt')
print(b)
print(type(b))
print(b.dtype)



# savetxt() and loadtxt() accept additional optional parameter such as header, footer & --------

<class 'numpy.ndarray'>
int32
[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
float64


In [21]:
# indexing using index array

import numpy as np
arr = np.arange(1,10,2)
print("Element of array: ",arr)
arr1 = arr[np.array([4,0,2,-1,-2])]
print("Indexed Element of array arr: ",arr1)

Element of array:  [1 3 5 7 9]
Indexed Element of array arr:  [9 1 5 9 7]


In [22]:
# indexing in 2 Dim

import numpy as np
arr = np.arange(12)
arr1 = arr.reshape(3,4)
print("Array arr1: \n" , arr1)
print("Element at eth row and eth column of arr1 is:" ,arr1[0,0])
print("Element at 1st row amd 2nd column of arr1 is:" ,arr1[1,2])


Array arr1: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Element at eth row and eth column of arr1 is: 0
Element at 1st row amd 2nd column of arr1 is: 6


In [23]:
# indexing in 3 Dim

import numpy as np
arr = np.arange(12)
arr1 = arr.reshape(2,2,3)
print("Array arr1: \n", arr1)
print("Element:",arr1[1,0,2])



Array arr1: 
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Element: 8


In [24]:
# Slicing 1D Numpy array

import numpy as np
arr = np.arange(6)
print("array arr: ",arr)
print("sliced element of array: ", arr[1:5])
print("sliced element of array: ", arr[-5:-1])

array arr:  [0 1 2 3 4 5]
sliced element of array:  [1 2 3 4]
sliced element of array:  [1 2 3 4]


In [26]:
# Slicing 2D array

import numpy as np
arr = np.arange(12)
arr1 = arr.reshape(3,4)

print("Array arr1: \n",arr1)
print("\n")
print("element of 1st row and 1st column upto last column \n", arr1[1:,1:4])

Array arr1: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


element of 1st row and 1st column upto last column 
 [[ 5  6  7]
 [ 9 10 11]]


# Broadcasting


In [1]:
import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print('First array:') 
print(a) 
print('\n')  
   
print('Second array:') 
print(b) 
print('\n')  
   
print('First Array + Second Array' )
print( a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


# Structured Array

In [2]:
#Python program to demonstrate
# Structured array
import numpy as np
a = np.array([('Sana', 2, 21.0), ('Mansi', 7, 29.0)], 
             dtype=[('name', (np. str_, 10)), ('age', np.int32), ('weight', np.float64)])
print(a)


[('Sana', 2, 21.) ('Mansi', 7, 29.)]


# Statisical function 

In [3]:
# there are mean , median ,avaerage , peak to peak , variance ,stndr deviations

import statistics

data_1 =[1,2,3,4,5]
x= statistics.mean(data_1)
print("mean is : ",x)

mean is :  3


In [4]:
import numpy as np 
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
arr + arr


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
arr - arr


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
arr/arr

C:\Users\karti\AppData\Local\Temp\ipykernel_8224\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [9]:
arr//arr


C:\Users\karti\AppData\Local\Temp\ipykernel_8224\3576654767.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  arr//arr


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [10]:
1/arr


C:\Users\karti\AppData\Local\Temp\ipykernel_8224\3166499923.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [11]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)